management.endpoints.web:
  exposure.include: info,health,prometheus
  base-path: /
  path-mapping:
    info: actuator/info
    health: health
    prometheus: actuator/prometheus

spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: ""
    username: ""
    password: ""
    hikari:
      idleTimeout: 45000
      connection-timeout: 3000
      validation-timeout: 3000
      maxLifetime: 50000
      minimum-idle: 0
      maximum-pool-size: 0

  flyway:
    enabled: false

info:
  version: 0.1.0

---
spring:
  config.activate.on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/TABLE_NAME?autoReconnect=true
    username: root
    password: local
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/TABLE_NAME
    user: root
    password: local

---
spring:
  config.activate.on-profile: development

---
spring:
  config.activate.on-profile: production

...
