version: '3.8'

services:
  db:
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: TABLE_NAME
    ports:
    - 3306:3306
    volumes:
    - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
    - 8090:8080
